SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST ON ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE AND ROBINST_STATUS_IND = 'A'
JOIN ROBNYUD ON ROBNYUD_PIDM = RORSTAT_PIDM
WHERE RORSTAT_AIDY_CODE = :AIDY
AND RORSTAT_PIDM = :PIDM
AND RORSTAT_APRD_CODE IN ('PA3', 'CADEF')
AND ROBNYUD_VALUE_197 = 'Y'
AND ROBNYUD_VALUE_198 = 'GR'
AND 
EXISTS (
    SELECT 1
    FROM SATURN.SGBSTDN E
    WHERE E.SGBSTDN_PIDM = RORSTAT_PIDM
    AND E.SGBSTDN_LEVL_CODE = ROBNYUD_VALUE_198
    AND E.SGBSTDN_MAJR_CODE_1 = ROBNYUD_VALUE_199
    AND E.SGBSTDN_DEGC_CODE_1 = ROBNYUD_VALUE_200
    AND E.SGBSTDN_STST_CODE IN ('AS', 'IL', 'P1')
    AND E.SGBSTDN_TERM_CODE_EFF = (
        SELECT MAX(F.SGBSTDN_TERM_CODE_EFF)
        FROM SGBSTDN F
        WHERE F.SGBSTDN_PIDM = E.SGBSTDN_PIDM
        AND F.SGBSTDN_TERM_CODE_EFF <= ROBINST_AIDY_END_YEAR || '10'
    )
)
;